export const FormsStatus = {
  personal_information: false,
  educational_background: false,
  job_preference: false,
  camp_information: false,
  work_experience: false,
  skills: false,
  personal_statement: false,
  medical_history: false,
  visa_informations: false,
  profile_image: false,
  program_agreement: false,
  payment_1: false,
  interview: false,
  video: false,
  reference: false,
  emergency_contact: false,
  payment_2: false,
  crb: false,
  passport: false,
  health_history_form: false,
  payment_3: false,
  flight_info: false,
  camp_contract: false,
  return_to_camp_invite: false,
  proof_of_student_status: false,
};
