export const PersonalInformation = {
  first_name: '',
  middle_name: '',
  last_name: '',
  gender: 'male',
  citizenship: 'US',
  dob: '01-01-2001',
  address_line1: '',
  address_line2: '',
  county_state: '',
  town_city: '',
  postcode: '',
  country: 'US',
  start_date: '',
  end_date: '',
  contact_number: '',
  city_of_birth: '',
  country_of_birth: '',
  driving_license: '',
  skype_name: '',
  telephone_dial_code: '',
  mailing_address: '',
  mobile_number: '',
  mobile_dial_code: '',
  social_media_links: '',
};
