export const StagesList = [
  {
    amount_due: null,
    due_amount: null,
    created_at: null,
    fee: null,
    id: 1,
    lateFee: null,
    name: 'Stage One',
    position: 1,
    returneeFee: null,
    returneeLateFee: null,
    updated_at: null,
  },
  {
    amount_due: null,
    due_amount: null,
    created_at: null,
    fee: null,
    id: 2,
    lateFee: null,
    name: 'Stage Two',
    position: 2,
    returneeFee: null,
    returneeLateFee: null,
    updated_at: null,
  },
  {
    amount_due: null,
    due_amount: null,
    created_at: null,
    fee: null,
    id: 3,
    lateFee: null,
    name: 'Stage Three',
    position: 3,
    returneeFee: null,
    returneeLateFee: null,
    updated_at: null,
  },
];
